on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Latest Release

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: jidicula/cloudflare-cachebuster/.github/workflows/build.yml@main
  release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
